name: sabalive
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: ^4.3.4
  flutter_swiper: ^1.1.2
  flutter_staggered_grid_view: ^0.3.0
  pin_code_text_field: ^1.6.0
  http: ^0.13.3
  flutter_rating_bar: 3.2.0+1
  intl: 0.16.1
  numberpicker: ^1.0.0
  flare_splash_screen: 3.0.1
  flutter_svg: ^0.22.0
  dio: 4.0.0
  shared_preferences:
  get_it: ^ 3.0.3
  fluttertoast: ^8.0.3
  image_picker: ^0.8.3+2
  flutter_image_compress: ^0.6.5+1
  path_provider:
  dropdown_formfield:
  stripe_payment: ^1.1.4
  firebase_core: ^1.4.0
  url_launcher:
  flutter_spinkit: ^4.1.2
  flutter_html:

dev_dependencies:
  effective_dart: 1.3.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
